### ISSUE TITLE
Delete data from DB

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#100]
As @Supryk mentioned here, maybe we can change this procedure. Anyway I would like to keep this as much secure as possible. I really wanna avoid any accidentaly deleted data during updating plugin (install/uninstall process)

**Comment by SvePu** [comment]
Yes...we can! ;)

**Comment by SvePu** [comment]
Please test it...for me it works fine.

**Comment by Cu8eR** [comment]
@SvePu - It works fine, thank you!
