### ISSUE TITLE
Some parts of code in templates are not deleted during uninstall

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#13]
Some parts of code in templates are not deleted during uninstall

for example code in post bit template in your theme

see: #2 

- post bit template:
-- postbit
-- postbit_author_user
-- postbit_classic

**Comment by Cu8eR** [comment]
@SvePu - please make a PR for all your fixes. I will merge it (or you can :) )

**Comment by SvePu** [comment]
I have tried to push the changed files here but it doesn't work

**Comment by Cu8eR** [comment]
OK, I will try

**Comment by Cu8eR** [comment]
@SvePu - merged :)
