### ISSUE TITLE
Remove unnecessary code from postbit templates

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#2]
Remove unnecessary code from postbit and postbit_classic
http://community.mybb.com/thread-59652-post-1109789.html#pid1109789

**Comment by Cu8eR** [comment]
![template](https://cloud.githubusercontent.com/assets/778890/5603749/c1132f52-9394-11e4-9e5b-b7137e2c0a7f.png)

**Comment by Cu8eR** [comment]
line 365 - there should be 3x </div> tags for replacement

**Comment by SvePu** [comment]
the reason of this is that the mybb find_replace function finds the searched templete parts 3 times

**Comment by Cu8eR** [comment]
@SvePu - yes, I checked it... could you fix it? All template changes are yours

**Comment by SvePu** [comment]
I'm looking for a solution

**Comment by Cu8eR** [comment]
@SvePu - also check please #13 - it is related to this

**Comment by SvePu** [comment]
yeah its the same reason

**Comment by SvePu** [comment]
Fixed it!
