### ISSUE TITLE
Version 1.7

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#20]
Do you have any ideas or plans what to add into next version? I think it looks fine, I will test latest changes tommorow.

Feel free to open a new issue with your idea/bug/PR :)

**Comment by SvePu** [comment]
For me it is ok now.... ready for release ;)

This version needs a completly new installation! But you can use the old entries in database.

**Comment by Cu8eR** [comment]
New version released. @SvePu - great work, amazing!

**Comment by Cu8eR** [comment]
https://github.com/Cu8eR/thankyou-like-plugin/releases/tag/v1.7
