### ISSUE TITLE
MyAlerts integration

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#21]
MyAlerts v2 supports custom modules. It would be nice to integrate alerts for Thankyou/like plugin in future.

**Comment by SvePu** [comment]
@Cu8eR Do you have a link to one of that modules?

**Comment by Cu8eR** [comment]
https://github.com/WildcardSearch/MentionMe/pull/78 

For example here - PR for MentionMe - add supports for MyAlerts v2

**Comment by Cu8eR** [comment]
@SvePu - maybe, we should wait for a final version of MyAlerts. Documentation is missing

**Comment by Cu8eR** [comment]
@SvePu - ok, link with manual how to integrate it

https://github.com/MyBBStuff/MyAlerts/wiki/Integration-With-v2.0.0

**Comment by Cu8eR** [comment]
@SvePu - I tried to add support for myalerts but without success... custom alert + setting for alerts is really easy to do but the rest is not as easy as I thought

**Comment by Cu8eR** [comment]
Merged, added! Thx to @WhiteNeo
