### ISSUE TITLE
Thank you/Like text in buttons

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#22]
What about to make <strong>Like/Thank you</strong> for buttons in post bit?

EDIT: just use strong and /strong to make the text bold

**Comment by Cu8eR** [comment]
@SvePu - what do you think? Just add a class for it in .css file for thankyoulike

**Comment by SvePu** [comment]
@Cu8eR User can edit text style in language files

eg: `['add_ty'] = "<strong>Add Thank You</strong>";`

**Comment by Cu8eR** [comment]
@SvePu - I know, which solution would be better? What do you think?

Edit lang file or edit thankyoulike .css file in mybb ACP? We should use a custom css class for this button and leave it normal, user can change it to "strong" in css

**Comment by SvePu** [comment]
OK...I didn't tested it.

You can style the font in buttons like this in g33k_thankyoulike.css

>a.add_tyl_button span{
>background-image: url(images/thankyoulike/thx_add.png);
>font-weight: bold;
>}
>
>a.del_tyl_button span{
>background-image: url(images/thankyoulike/thx_del.png);
>font-weight: bold;
>}

**Comment by Cu8eR** [comment]
So we should add this change into our .css file but use font-weight:normal

**Comment by SvePu** [comment]
Done!

**Comment by Cu8eR** [comment]
Thank you!
