### ISSUE TITLE
Make <hr> dotted in post bit

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#23]
It would be better to use a dotted line - same style like under avatar picture on the left

![dotted](https://cloud.githubusercontent.com/assets/778890/5702148/27c5dd04-9a56-11e4-8ec5-ba8ccf22ef48.png)

code for this change:
 {
  border-top: 1px dotted #ccc;
	color: #ffffff;
	height: 1px;
	width: 100%;
  	margin-left: auto;
    margin-right: auto;
}

Also the list with thanks/like is too high - its height shoul be smaller - padding between title and users should be smaller

**Comment by SvePu** [comment]
User can style the ThankYou/Like list in g33k_thankyoulike.css file.
Example for list in classic layout:
>.tyllist_classic{
>    border-bottom: 1px dotted #ccc;
>    padding: 2px 5px;
>    color: #555;
>}

![tyllist_classic_style](https://cloud.githubusercontent.com/assets/9826631/5788881/87c48a1c-9e51-11e4-8fa0-adbff9600eef.JPG)

**Comment by Cu8eR** [comment]
Of course, but I think this hr style should be default in plugin - we should use same hr style which is used in post bit

**Comment by SvePu** [comment]
We can also add it as default.

Which hr style in postbit do you mean?

**Comment by Cu8eR** [comment]
Sorry, I mean <div class="author_statistics"> under the avatar in post bit classic. We should use same style for our hr in thank you like

**Comment by Cu8eR** [comment]
So the .css code should be:
border-top: 1px dotted #ccc;
color: #ffffff;
height: 1px;

**Comment by SvePu** [comment]
Sorry, but I can't see a `<hr>` line in postbit template.

**Comment by Cu8eR** [comment]
@SvePu - what about color: #ffffff? Because the dotted line has a white background without this, am I right? At least I had to add this into my css file on my forum
