### ISSUE TITLE
Improve exclude forum selection

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#26]
What about to add click to select forums where to disable thank you/like system? It would be better than write numbers.

@SvePu

**Comment by SvePu** [comment]
That's the way I would include it. ;)

**Comment by Cu8eR** [comment]
@SvePu - can you add this?

**Comment by SvePu** [comment]
Added option in e46072e52b6d88841c53eb290ca76d8ac179610b

**Comment by Cu8eR** [comment]
@SvePu - just a question - is there is any way how to add support for categories? Now it is not possible. I will check more after I come home. Thank you!
