### ISSUE TITLE
IPv6 users can't use the search links in the user profile

### ISSUE THREAD

**Issue by Evenprime** [Cu8eR/thankyou-like-plugin#29]
Currently there exists a problem with IPv6 users in MyBB 1.8.x, where they can't use the four quick search links in another users profile (liked threads, liked posts, posts with likes, threads with likes). A MySQL error is thrown because the value for the ipaddress field is too long.

The problem is in "tylsearch.php":
`"ipaddress" => $db->escape_string($session->ipaddress),`
has to be replaced with
`"ipaddress" => $db->escape_binary($session->packedip),`

for the inserts into the 'searchlog' table.

**Comment by Cu8eR** [comment]
Thank you for you bug repport. Only this line has to be change? Or do you
have any more suggestions?

**Comment by Cu8eR** [comment]
@Evenprime @SvePu - I made a PR for this issue - could you please check this? Thank you!

**Comment by Evenprime** [comment]
Yes, that's exactly what I meant and what fixed the problem for my IPv6 user(s).

Sorry that I didn't create a PR myself, because I currently don't have access to my usual development PC.

**Comment by Cu8eR** [comment]
OK, thanks! It is OK, feel free to report more ideas and bugs :)
