### ISSUE TITLE
List of users stays hidden after you remove and add a thank/like

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#38]
List of users stays hidden after you remove and add a thank/like even you set show collapsed in setting

How to reproduce:
- enable thanks/like removing
- enable list collapsive
- set default collapsive state to: "List shown"

Everything works fine until you add and then without refreshing remove your thank/like from a post and add again thank/like for a same post.

I am not good in JS so I dont know how to fix that :(

**Comment by Cu8eR** [comment]
@WhiteNeo - I am not good at JS, or I dont know how to fix that. Problem still persists.

How to reproduce?
- enable thanks/like removing
- enable list collapsive
- set default collapsive state to: "List shown"
- add thank/like to the post
- remove thank/like to same post
- add again thank like to the post

-> list of users is hidden, it should respect setting and be collapsed and shown

**Comment by WhiteNeo** [comment]
I have to review it again i tested with one and two likes because not have more.

I can not reproduce it and i need to do to find a fix. By the way i set thay opts and test on posts as you said but i sm using Mozilla Firefox allways if you have some more info to reproduce bug it is for sure this can be fixed asap.

**Comment by Cu8eR** [comment]
I can reproduce it in Chrome and Firefox. 

I can provide you a testing board - just PM me at MyBB forum for password.

**Comment by Cu8eR** [comment]
@WhiteNeo - I sent you a PM with all info inside. I think that JS script ignores setting for list (hide or shown state when you do not reaload page).

**Comment by Cu8eR** [comment]
@WhiteNeo - please sync latest changes into your branch - I merged all your latest changes here, please use this branch for development

https://github.com/Cu8eR/thankyou-like-plugin/tree/feature_jGrowl_DarkNeo

**Comment by Cu8eR** [comment]
Should be fixed via https://github.com/Cu8eR/thankyou-like-plugin/commit/3b5cbe4990f2d79b1b3cda1fe1568319884055d0
