### ISSUE TITLE
Allow adding like/thank in closed threads for users

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#4]
Allow adding like/thank in closed threads for normal users. Now only moderators/administrators can do that... New setting should be added instead of hard coded value

http://community.mybb.com/thread-59652-post-1128203.html#pid1128203

**Comment by Cu8eR** [comment]
@SvePu - what do you think?

**Comment by SvePu** [comment]
I've tried but it doesn't work yet

**Comment by Cu8eR** [comment]
I have tried too, but same result...

**Comment by SvePu** [comment]
I've figured it out! ;)

**Comment by Cu8eR** [comment]
@SvePu - amazing! Just a one thing - I havent checked the code but:
- is possible to enable/disable this feature to only some usergroups?

**Comment by Cu8eR** [comment]
@SvePu - I cannot merge your latest changes . many conflicts :(

**Comment by SvePu** [comment]
What kind of conflicts??

**Comment by Cu8eR** [comment]
merge conflict - so is possible to sync your branch with master branch here before your changes? If not, dont worry

**Comment by SvePu** [comment]
@Cu8eR dont know what you mean.. :)

**Comment by Cu8eR** [comment]
There are some problems with merging your changes into this master branch. I will try to solve this :(
