### ISSUE TITLE
Show date and time on a mouse hover

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#5]
Show date and time on a mouse hover for nicknames. 

http://community.mybb.com/thread-59652-post-1128322.html#pid1128322

**Comment by Cu8eR** [comment]
Done!

**Comment by SvePu** [comment]
we can integrate a settings option to choose where the date/time should be displayed

**Comment by Cu8eR** [comment]
OK, so I reopen this. 

Anyway, I think date/time in title tag is better

**Comment by SvePu** [comment]
I guess too, but maybe someone want it next to username.

**Comment by Cu8eR** [comment]
@SvePu - can I assign this issue to you?

**Comment by SvePu** [comment]
Yes... I'll add an option to choose date display position tomorrow

**Comment by SvePu** [comment]
settings option is integrated now
