### ISSUE TITLE
Popup notification - feature requests

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#61]
Just everything in one issue, is it possible? What do you think

- use same style like MyBB popup notifications
- turn on/off
- is possible to have a lang var for "CLOSE ALL"?
- anything else?

@WhiteNeo

**Comment by WhiteNeo** [comment]
That is a MyBB core feature and not plugin.

Go to jquery.plugins.min.js and search for jgroul default values and there you can see all content you wanna change, like the close all and all other things like modal boxes, etc.

**Comment by Cu8eR** [comment]
OK, I didnt know this :)
