### ISSUE TITLE
() is shown in alert notification window

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#66]
link: http://community.mybb.com/thread-169382-post-1160848.html#pid1160848

As @Euan wrote in this post (http://community.mybb.com/thread-169382-post-1161017.html#pid1161017 ), we just need to adjust lang file and users have to use latest MyAlerts version (2.0.1 and higher).

**Comment by euantorano** [comment]
> and users have to use latest MyAlerts version (2.0.1 and higher).

`2.0.0` and higher should suffice, but `2.0.1` is more stable :smile:
