### ISSUE TITLE
Apostrophes are not being parsed

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#70]
@WhiteNeo - new bug has been found. It is related only to thankyou/like plugin. Every other plugin with myalerts support shows apostrophes correctly.

![bugb](https://cloud.githubusercontent.com/assets/778890/8270888/855e9d3a-17fa-11e5-8e67-10e7506bae8a.png)

![fc4e87be-17c0-11e5-9f4f-1ee6931b675b](https://cloud.githubusercontent.com/assets/778890/8270889/8fb49aa0-17fa-11e5-89f3-8fbfac92d792.jpg)

**Comment by Cu8eR** [comment]
@WhiteNeo - hi, do you have any idea how to fix this?

**Comment by WhiteNeo** [comment]
Fixed some days ago, but i'm waiting to see if new issues are coming up and maybe add some new things on this release, and fix all to make a very stable mod like mnes right now :dancer: 
All my mods working like a charm, so i think maybe next mission is to make a new plugin for some user on official forum and work in this one.

**Comment by Cu8eR** [comment]
Fixed. Working fine, no issues have been found on my test board. @WhiteNeo - thank you very much!
