### ISSUE TITLE
Promotion Requirement

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#75]
I would like to ask as well if it's possible to add this as a 'Promotion Requirement' under Users & Groups > Group Promotions?

link: http://community.mybb.com/thread-169382-post-1180173.html#pid1180173

**Comment by Cu8eR** [comment]
Maybe we can take idea from here:
https://github.com/Sama34/Newpoints-Promotion-System-Integration/blob/master/Upload/inc/plugins/newpoints/newpoints_promotion.php

**Comment by Cu8eR** [comment]
@WhiteNeo @SvePu 

Guys, do you have any idea if it is possible to add without complete rewrite of plugin? Thanks

**Comment by SvePu** [comment]
Unfortunately I have no experience with the "newpoints" plugin.

**Comment by Cu8eR** [comment]
@SvePu - it is just an example for adding option into MyBB group promotion system. I mean, you can set for example: user needs 20 obtained likes/thanks to be promoted to higher rank

**Comment by SvePu** [comment]
@Cu8eR OK...I'll take a look at this. ;)

**Comment by Cu8eR** [comment]
Thank you... this is one of the most wanted feature after MyAlerts integration :)

**Comment by Cu8eR** [comment]
@SvePu - do you haveany idea how to do that?

**Comment by SvePu** [comment]
....not yet - I'm thinking :)

**Comment by Cu8eR** [comment]
@SvePu - Hi, I would like to release v1.9.10 soon, anyway is there any chance to get this feature into TYL system?

**Comment by SvePu** [comment]
I'm already don't know how to start with something like this - maybe @Sama34 could give us some help?!

**Comment by Sama34** [comment]
Just add a new field to the promotion system for required amount:
https://github.com/Sama34/Newpoints-Promotion-System-Integration/blob/master/Upload/inc/plugins/newpoints/newpoints_promotion.php#L150

Hooking at the promotion task is the easy part:
https://github.com/Sama34/Newpoints-Promotion-System-Integration/blob/master/Upload/inc/plugins/newpoints/newpoints_promotion.php#L201

Adapting my plugin could be easier that inserting it into this plugin core.

**Comment by SvePu** [comment]
@Sama34 : Thanks Omar, I'll take a look.

**Comment by Cu8eR** [comment]
@Sama34 - Thank you for your hint! I really appreciate it!

**Comment by SvePu** [comment]
Included such function....please test it.

**Comment by Cu8eR** [comment]
Perfect, I will test is soon I will relase a beta version and add a link into topic in MyBB forum... More testers, better for us!

**Comment by SvePu** [comment]
I've tested it and it works fine...

**Comment by Cu8eR** [comment]
@SvePu - I will, I tested it localy and without any issue. At least for me. I will release 1.9.10 soon.

Do you have any ideas what is missing in TYL system and what can be added into next version? I have some ideas, but it would be wawesome to get any feedback from community and you
