### ISSUE TITLE
Multiple notifications for one topic - MyAlert integration

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#80]
One topic and Two replies or Two Likes for example . myalerts shows two notifications . I go to the thread with two then shows me always myalerts yet an alarm . Although both are mutually likes .

http://community.mybb.com/thread-171301-post-1182055.html#pid1182055

**Comment by WhiteNeo** [comment]
Fixed...

**Comment by Cu8eR** [comment]
Thank you very much! I will test it today!
