### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#82]
SQL error in a thread (when TYL system is activated)... index of forum works fine, just in every thread where any post is thanked/liked -> this error

Is there any way how to fix this without losing any DB data? Uninstall and install didnt help
![sql error](https://cloud.githubusercontent.com/assets/778890/9821417/7686a4d2-58ba-11e5-859b-b5180201dac3.png)

**Comment by WhiteNeo** [comment]
I see the code but you can review it line 780 talks about that, but is a trim($pids), i have to reproduce error, any idea on how to ?

Nothing have to lose, but if i'm fine i think if remove this trim and use only $pids caansolve this issue, however we have to review why this error appear now and not before :o2:

**Comment by WhiteNeo** [comment]
If you told mehow to reproduce it thismay help to me, i think it's a multi post like in same thread, due that query but i can not reproduce it yet.

That part of code does not changed.

**Comment by Cu8eR** [comment]
@WhiteNeo - it is not problem on my forum, it is a PM from one of the users from MyBB community forum.

He just disable and enable TYL System after 1.8.6 MyBB upgrade. This error is shown everytime in a thread where any thanks/like was added.

**Comment by Cu8eR** [comment]
I just cannot see the reason why to use "trim" here

**Comment by Cu8eR** [comment]
@WhiteNeo - please could you prepare for me one testing version with your proposed changes? I will send it to the user with this issue

Thank you!

**Comment by WhiteNeo** [comment]
I can not find nor reproduce this error i do what you say and no way to found it.

I have to reproduce, because that trim haave no effect on that strange weird thing, in that users case table or code tyl.nm is a very strange value so if i change or delete that does not change nothing, because i think is an users error due some code changes on templates or bug inside their db.

**Comment by Cu8eR** [comment]
OK, so DB must be corrupted

**Comment by WhiteNeo** [comment]
Unfortunatelly i think so. I'm testing yet and all goes fine in this latest released version but o dunno, maybe can exist some bugs, but if i found some i fix it and comment on code changes.

**Comment by Cu8eR** [comment]
I got PM that DB is not corrupted, the user tried to repair and check DB for errors but nothing was found. I will try to get pw/username to test it on its forum.

**Comment by Cu8eR** [comment]
@WhiteNeo - OK, user has a backup of DB before it started and backup after the error occured. Can you check them when I send you them? It is only thankyoulike table...

**Comment by WhiteNeo** [comment]
If you have the error version this should help to make some tests

Only send me if you can that db files and it's all, i don't need an account or any, only that db to test it and reproduce error for i can fix it, thanks.

**Comment by Cu8eR** [comment]
@WhiteNeo - I cannot reproduce it, I think there must be something wrong with MyBB core files - is there any way how to easily find this string which causes this problem in which file? 

Thank you/like system looks fine, there is nothing wrong. The suer wrote me,that he wipe out the thankyoulike DB table fully and error persists. So do you have any idea where to find in MyBB core files? What is related? Thank you!

**Comment by WhiteNeo** [comment]
Without reproducing i really doubt it.

**Comment by Cu8eR** [comment]
OK, I am closing... without more info I cannot fix it or reproduce it. It must be a conflict with something in core MyBB files or with any other plugin
