### ISSUE TITLE
Hide thanks/like list under the post for guest

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#84]
Now we can hide thanks/like button for specific group of users (guest, awaiting registration, etc.) in postbit

We should add setting to hide thx/like list under the post for specific groups too.

My idea?
Just add new option for this (same as for hide/show thx/like button)

http://community.mybb.com/thread-169382-post-1183766.html#pid1183766

@WhiteNeo - I am not sure about this, is it difficult to add? Because it would take another query to DB if I am right. Anyway this should be optional.

**Comment by OMID-F** [comment]
is this really needed? i don't see reason to do this

**Comment by SvePu** [comment]
I added a settings option to hide the ThankYou/like list from specific user groups.

English admin translations are addapted - spanish lang files are prepared but not translated

**Comment by Cu8eR** [comment]
@SvePu - welcome back my friend! Thank you for your contribution :)
