### ISSUE TITLE
Install plugin templates not as global templates

### ISSUE THREAD

**Issue by SvePu** [Cu8eR/thankyou-like-plugin#85]
Hey,
I guess it will be better when we switch the template insertion from global templates to theme specific ones. By this way plugin templates can be modified separately for each theme.

What do you think?

**Comment by Cu8eR** [comment]
I agree, it would solve many issues with custom themes. There should not be
any side effect of this.

If you can do it, feel free.

**Comment by WhiteNeo** [comment]
I think this is the best way to do actually i got in this way in my plugin for that reason of many users like to customize all for every theme, so i let th users can do :D. If you want to do or whatever let my know maybe can help on some new additions or deletions.

**Comment by Cu8eR** [comment]
Yes, I agree. This would be perfect. Lately we got many questions and issues about customizing from users who use custom (not MyBB default one) theme.

**Comment by SvePu** [comment]
I changed plugin template insertion from global to theme specific ones.
