### ISSUE TITLE
Multiple adding JS into showthread template

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#86]
Code for JS is added multiple times in template "show thread templates -> showthread" after activation/deactivation and again activation

```
<script type="text/javascript">
<!--
	var tylEnabled = "{$mybb->settings['g33k_thankyoulike_enabled']}";
	var tylCollapsible = "{$mybb->settings['g33k_thankyoulike_collapsible']}";
	var tylUser = "{$mybb->user['uid']}";
	var tylSend = "{$lang->tyl_send}";
	var tylRemove = "{$lang->tyl_remove}";
-->
</script>
```
It should be deleted/reverted but is it not

**Comment by Cu8eR** [comment]
@SvePu - please, could you check this together with #85 ? Thanks

**Comment by WhiteNeo** [comment]
I think that code can be removed and use a new var to do all, i use this system on my own mod and now it's to easy to add new implementations of code and users haven't to move nothing only upload new files and done !!!

Sometimes in few cases have to run uninstall and install again but for new code improvments only.

I use a var hooked to global and load with templates and there let all script code, i think is better for me at least let me add more new code improvements to easy :D.

As the other thing of templaates let me know if some help is needed.

Anyway i let to Sven to work in this :D

**Comment by Cu8eR** [comment]
@WhiteNeo - I agree, var should be used here. It should solve multiple loading of JS for many users who dont know about multiple adding this into showthread template

**Comment by SvePu** [comment]
Now adding and removing of this works - but user have to remove the previous entries manually. - Sorry - there is no other way!

**Comment by Cu8eR** [comment]
@SvePu - thank you, great! I will add a note about this into changelog when we release 1.9.8

We need to test everything and v1.9.8 could be release soon (maybe on Sunday?)

**Comment by SvePu** [comment]
I've tested it in local server and everything works fine. If you like we can release new version now. :)

**Comment by Cu8eR** [comment]
@SvePu - I have no problem with that,

Maybe just one idea:
- minify JS for Thankyoulike plugin and load this minified version instead of the normal unminified version by default. Normal version file of JS just include in plugin archive for easier modifications and changes. What do you think? We can save some kB on every page load

**Comment by SvePu** [comment]
Added in https://github.com/Cu8eR/thankyou-like-plugin/commit/ab832ce0e8ea46c206ff179ca8a6d6294f2aa0a6

**Comment by Cu8eR** [comment]
@SvePu - thx!
