### ISSUE TITLE
Template changes should NOT be added/reverted during activate/deactivate procedure

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#87]
Now all templates changes are reverted after deactivation and added back after activation procedure... I think ithis is not the best solution - mainly if you wanna update plugin - it brings a lot of extra work with adding and customization of code

Is possible to change this? I prefer to add code into template during instalation and revert them after uninstall... so keep everything unchanged during activate/deactivate

**Comment by SvePu** [comment]
I fixed this in https://github.com/Cu8eR/thankyou-like-plugin/commit/c0708f62dddf336c54cc02e239ac2d76b9fdc1bf

Only plugin settings and template modifications will removed on deactivation.
