### ISSUE TITLE
Multiple voting in a post by one user?

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#9]
Some users on my forum accidentally discovered a race condition which allows someone to like a post multiple times - there is a millisecond (or so) long window between checking for an existing like and inserting the like. Under the right conditions (The first few times it happened it was accidental) or with a flood of requests a post can end up with two likes from one user.

The solution was to change the index on (pid, uid) to a unique key as opposed to just a plain ol' index.

Fix and more info are here:
http://community.mybb.com/thread-59652-post-1073519.html#pid1073519

**Comment by Cu8eR** [comment]
@SvePu - what do you think? I cannot reproduce the issue which is mentioned in the post above...

**Comment by SvePu** [comment]
Dont know... I can't reproduce it too but I added the linked fix ;)

**Comment by Cu8eR** [comment]
OK, I hope it wont have any side-effects.

Do you have any other ideas what to fix or improve? Because there is only
one issue (enchantement) for voting in closed threads. Unfortunately I
cannot find a way how to make it working.

Feel free to open an issue for any improvement or idea

**Comment by SvePu** [comment]
Next I'll try to get voting in closed threads working. Could you merge the updated plugin files?

**Comment by Cu8eR** [comment]
Yes, of course. I will merge the changes in the evening, I am at work now

**Comment by SvePu** [comment]
OK...thank you!

**Comment by Cu8eR** [comment]
Fixed!
