### ISSUE TITLE
Recounting thanks/likes in ACP

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#90]
It would be nice to change this process. Without a lot of clicking on "process" button - just one click which starts the whole process. This approach is used for MyBB recount and rebuild page where only one click is needed

**Comment by SvePu** [comment]
Also can't reproduce this - it works fine.
![tyl_03](https://cloud.githubusercontent.com/assets/9826631/11121109/5b032b66-8954-11e5-83f8-3a029d5cc089.PNG)

..but I've rewrite the ACP rebuild module

**Comment by Cu8eR** [comment]
@SvePu - thx, I will try later when I get home.

**Comment by Cu8eR** [comment]
OK, is there any way how to do it automatically (same way as MyBB recounting?). This I mean, when there are more entries than you set and click to go, there is a message shown - automatic redirecting - you dont have to click again and again on proceed button.

If it is not possible, please close this. Thank you for your security fix!

**Comment by Cu8eR** [comment]
@SvePu - I am closing this issue, not high priority and I didnt find any way how to change it

**Comment by SvePu** [comment]
Try it.... ;)

**Comment by Cu8eR** [comment]
Amazing! Great! Works fine!
