### ISSUE TITLE
Date and time is same for every users thanks/like received in search

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#91]
http://community.mybb.com/post-1197105.html#pid1197105

Confirmed - time is same for every post/thread

**Comment by Cu8eR** [comment]
![bug1](https://cloud.githubusercontent.com/assets/778890/11114814/93aa1146-8927-11e5-9573-fc89c4f18db9.png)

**Comment by SvePu** [comment]
Fixed it...
![tyl_02](https://cloud.githubusercontent.com/assets/9826631/11119951/412cac00-894d-11e5-9254-aec659bfc1d8.PNG)

**Comment by Cu8eR** [comment]
Good job!

**Comment by Cu8eR** [comment]
OK, tested and works fine! Fixed!
