### ISSUE TITLE
POST icon is in the wrong collumn

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#92]
In the search page, there is a problem with thread/post icon placement

![bug2](https://cloud.githubusercontent.com/assets/778890/11114859/f808f012-8927-11e5-8ab1-e3bfd99b766f.png)

**Comment by SvePu** [comment]
Can't confirm this 
![tyl_01](https://cloud.githubusercontent.com/assets/9826631/11119797/542fb758-894c-11e5-8813-e8a0fcd9bba5.PNG)

**Comment by Cu8eR** [comment]
Strange, I can confirm this on my live board. Maybe I am missing something

**Comment by SvePu** [comment]
Please try the new tylsearch.php => https://github.com/Cu8eR/thankyou-like-plugin/blob/master/tylsearch.php

**Comment by Cu8eR** [comment]
@SvePu - still same issue. Here are the screenshots

![devlopermode](https://cloud.githubusercontent.com/assets/778890/11127466/c6c3c714-8974-11e5-8887-09b601d01c10.png)
![developermode2](https://cloud.githubusercontent.com/assets/778890/11127475/cbf4636a-8974-11e5-9f45-431834fd4964.png)

**Comment by Cu8eR** [comment]
OK, @SvePu I have found an issue - it works only for thread icon, NOT for post icon :) here is the screen

![bug](https://cloud.githubusercontent.com/assets/778890/11130071/5e63665c-8983-11e5-8b12-4ea2aef78fe2.png)
