### ISSUE TITLE
Settings - enable/disable ajax popup alerts

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#93]
In thread about TYL system there is a feature request - enable/disable showing of ajax popup messages in the right corner. Is there any way? Style is used from MyBB, so it can be changed easily, but is possible to disable this easily?

![popup](https://cloud.githubusercontent.com/assets/778890/11127562/2bb4e5c2-8975-11e5-8e2f-f2db909f5832.png)

**Comment by SvePu** [comment]
Added settings option to disable displaying of Ajax popup notification

**Comment by Cu8eR** [comment]
@SvePu - thank you!
