### ISSUE TITLE
Search - ordering is wrong

### ISSUE THREAD

**Issue by Cu8eR** [Cu8eR/thankyou-like-plugin#94]
In likes/thanks received there is an issue with sorting (asc). I can confirm that
![2015-11-13_113235](https://cloud.githubusercontent.com/assets/778890/11144311/fce20d24-89fb-11e5-85b2-bdb1f6e744b3.png)

**Comment by Cu8eR** [comment]
@SvePu - this is the last issue which should be solved for the next release v1.9.9. I will have time next week to review this issue when I get home.

**Comment by SvePu** [comment]
I've a fix for that but I can't test it - too low thanks on my test forum

**Comment by Cu8eR** [comment]
Push it please into master branch, I will test it

**Comment by SvePu** [comment]
Done... ;)

**Comment by Cu8eR** [comment]
Works fine! Thank you and good job!
